### ISSUE TITLE
Why not use OS X's security tool instead of keychain-helper?

### ISSUE THREAD

**Issue by seanknox** [boxen/boxen#169]
I trolled through the project history but this still wasn't clear to me.

- OS X's default `/usr/bin/security` tool can be used to create and find tokens in the keychain. The keychain-helper binary in https://github.com/boxen/boxen says its purpose is to "provide isolation and a friendly message in security prompts".  I'm not sure what "isolation" implies and I'd assume handling output/exit codes from  `security` is easy enough to do. What advantage does using this custom C binary provide over using the default OS X tool?
- Additionally, I saw that a previous PR that proposed renaming the `Boxen` binary to `KeychainHelper` or similar that was rejected as it's named `Boxen` "specifically to make keychain unlock dialogs more clear".  The binary's single purpose is to help work with the OS X keychain. Wouldn't renaming the file to match its corresponding `.c` name make more sense and clue users as to its actual purpose, e.g. `keychain-helper`?

**Comment by seanknox** [comment]
@rafaelfranca @mikemcquaid what are your thoughts on this? automatically setting `GITHUB_API_TOKEN` for boxen runs was brought up in https://github.com/boxen/our-boxen/pull/732#discussion_r26906238—think this is relevant.

**Comment by rafaelfranca** [comment]
I'm out of the context here since I don't know the original reasons to create this custom C binary but maybe @jbarnette could help us.

**Comment by mikemcquaid** [comment]
I also lack context here, I'm afraid.

**Comment by seanknox** [comment]
@jbarnette can we get your input sir?

**Comment by mikemcquaid** [comment]
What is/are the problems that are caused by using the custom binary?

**Comment by seanknox** [comment]
It's a seemingly likely unnecessary dependency. I'd like to reduce these, simplify, and use existing tools already present on OS X instead of custom-built, unmaintained binaries.

**Comment by mikemcquaid** [comment]
@seanknox I've not been working on Boxen for a long time but I've been one of the Homebrew maintainers/core team for 6 years so hopefully my advice has some weight here (and this is speaking outside of my GitHub role as it's a Saturday :wink:): I really advice against changing old, clunky code that works with newer, shiny code. If it's fixing user bugs and you've tried fixing the old code and either cannot or it keeps breaking: cool (but I'd love to see the bug reports). Otherwise you risk just adding more bugs and making the experience more unpleasant for users just to make programmers a bit more happy. Unfortunately this happens often in open-source.

If you'd like/need access to the source: that's cool and I'm sure we can find a way to get you access to that.

**Comment by thedavidmeister** [comment]
So this issue would then become "document the old, clunky code explaining why it's needed"? Sure it works, but without an explanation of what its existence is guarding against, there's always the temptation to swap it out for a native OS solution for maintainability/simplicity reasons, and no way to ever re-assess whether the latest new and shiny has addressed the original problem or not.

**Comment by mikemcquaid** [comment]
@thedavidmeister As said above: if there's bugs that need fixed we should fix them but if it's just programmer preference we should not change it (as we'll add new bugs).

**Comment by thedavidmeister** [comment]
and even if it's just programmer preference, we should document it to say as such, or there'll always be the temptation to swap it out for a native OS solution as, by definition, that's programmer's preference

**Comment by mikemcquaid** [comment]
@thedavidmeister I don't have any more information than I've posted here and the people who originally worked on Boxen have moved on to other things so I'm :+1: on more documentation but we can't rely on others to write it.

**Comment by thedavidmeister** [comment]
Well if everyone who knows what it is is gone, that sounds like a meta-bug then, which is one reason to get rid of the custom thing, even if it causes some short term issues.

**Comment by mikemcquaid** [comment]
I disagree. Again: I disagree with changing things that are working unless you are fixing issues for end-users.

**Comment by rafaelfranca** [comment]
> I disagree. Again: I disagree with changing things that are working unless you are fixing issues for end-users.

:+1:. I also disagree

**Comment by thedavidmeister** [comment]
That's fine, I agree to disagree with you.

Code that is by definition unmaintainable (nobody knows why it was written or what about it can't be changed) is a bug because sooner or later you *will* need to change it (some future OS update that is incompatible with the "helper") and then you'll have double trouble - can't change it (because you don't know what bit can't be changed) and can't not change it (because it no longer works).

**Comment by seanknox** [comment]
I'm with @thedavidmeister—as maintainers/contributors of the project, we should know the purpose behind our code and ensure it's tested. 

I think everyone has chosen a stance on this issue—perhaps we can revisit it in the future.

**Comment by mikemcquaid** [comment]
> I'm with @thedavidmeister—as maintainers/contributors of the project, we should know the purpose behind our code and ensure it's tested.

Sure, I definitely agree with this as an ideal case. I wouldn't hold up Boxen as a well-run/documented open-source project personally. The question here is what we do now and I think it's totally reasonable to replace it either when we hit problems or when there's sufficient test coverage to be confident that the replacement is working. Personally I don't have time to work on either unfortunately (most of my open-source time is spent on Homebrew) but I'm happy to review if people CC me.
